sbatch convex_slurm.sh cit.POMDP_1_4
sbatch convex_slurm.sh fourth.POMDP_1_4
sbatch convex_slurm.sh mit.POMDP_1_4
sbatch convex_slurm.sh pentagon.POMDP_1_4
sbatch convex_slurm.sh sunysb.POMDP_1_4
sbatch convex_slurm.sh cit.POMDP_1_5
sbatch convex_slurm.sh fourth.POMDP_1_5
sbatch convex_slurm.sh mit.POMDP_1_5
sbatch convex_slurm.sh pentagon.POMDP_1_5
sbatch convex_slurm.sh sunysb.POMDP_1_5
sbatch convex_slurm.sh cit.POMDP_1_6
sbatch convex_slurm.sh fourth.POMDP_1_6
sbatch convex_slurm.sh mit.POMDP_1_6
sbatch convex_slurm.sh pentagon.POMDP_1_6
sbatch convex_slurm.sh sunysb.POMDP_1_6
sbatch convex_slurm.sh cit.POMDP_1_7
sbatch convex_slurm.sh fourth.POMDP_1_7
sbatch convex_slurm.sh mit.POMDP_1_7
sbatch convex_slurm.sh pentagon.POMDP_1_7
sbatch convex_slurm.sh sunysb.POMDP_1_7
sbatch convex_slurm.sh cit.POMDP_2_4
sbatch convex_slurm.sh fourth.POMDP_2_4
sbatch convex_slurm.sh mit.POMDP_2_4
sbatch convex_slurm.sh pentagon.POMDP_2_4
sbatch convex_slurm.sh sunysb.POMDP_2_4
sbatch convex_slurm.sh cit.POMDP_2_5
sbatch convex_slurm.sh fourth.POMDP_2_5
sbatch convex_slurm.sh mit.POMDP_2_5
sbatch convex_slurm.sh pentagon.POMDP_2_5
sbatch convex_slurm.sh sunysb.POMDP_2_5
sbatch convex_slurm.sh cit.POMDP_2_6
sbatch convex_slurm.sh fourth.POMDP_2_6
sbatch convex_slurm.sh mit.POMDP_2_6
sbatch convex_slurm.sh pentagon.POMDP_2_6
sbatch convex_slurm.sh sunysb.POMDP_2_6
sbatch convex_slurm.sh cit.POMDP_2_7
sbatch convex_slurm.sh fourth.POMDP_2_7
sbatch convex_slurm.sh mit.POMDP_2_7
sbatch convex_slurm.sh pentagon.POMDP_2_7
sbatch convex_slurm.sh sunysb.POMDP_2_7
sbatch convex_slurm.sh cit.POMDP_3_4
sbatch convex_slurm.sh fourth.POMDP_3_4
sbatch convex_slurm.sh mit.POMDP_3_4
sbatch convex_slurm.sh pentagon.POMDP_3_4
sbatch convex_slurm.sh sunysb.POMDP_3_4
sbatch convex_slurm.sh cit.POMDP_3_5
sbatch convex_slurm.sh fourth.POMDP_3_5
sbatch convex_slurm.sh mit.POMDP_3_5
sbatch convex_slurm.sh pentagon.POMDP_3_5
sbatch convex_slurm.sh sunysb.POMDP_3_5
sbatch convex_slurm.sh cit.POMDP_3_6
sbatch convex_slurm.sh fourth.POMDP_3_6
sbatch convex_slurm.sh mit.POMDP_3_6
sbatch convex_slurm.sh pentagon.POMDP_3_6
sbatch convex_slurm.sh sunysb.POMDP_3_6
sbatch convex_slurm.sh cit.POMDP_3_7
sbatch convex_slurm.sh fourth.POMDP_3_7
sbatch convex_slurm.sh mit.POMDP_3_7
sbatch convex_slurm.sh pentagon.POMDP_3_7
sbatch convex_slurm.sh sunysb.POMDP_3_7
sbatch convex_slurm.sh cit.POMDP_4_4
sbatch convex_slurm.sh fourth.POMDP_4_4
sbatch convex_slurm.sh mit.POMDP_4_4
sbatch convex_slurm.sh pentagon.POMDP_4_4
sbatch convex_slurm.sh sunysb.POMDP_4_4
sbatch convex_slurm.sh cit.POMDP_4_5
sbatch convex_slurm.sh fourth.POMDP_4_5
sbatch convex_slurm.sh mit.POMDP_4_5
sbatch convex_slurm.sh pentagon.POMDP_4_5
sbatch convex_slurm.sh sunysb.POMDP_4_5
sbatch convex_slurm.sh cit.POMDP_4_6
sbatch convex_slurm.sh fourth.POMDP_4_6
sbatch convex_slurm.sh mit.POMDP_4_6
sbatch convex_slurm.sh pentagon.POMDP_4_6
sbatch convex_slurm.sh sunysb.POMDP_4_6
sbatch convex_slurm.sh cit.POMDP_4_7
sbatch convex_slurm.sh fourth.POMDP_4_7
sbatch convex_slurm.sh mit.POMDP_4_7
sbatch convex_slurm.sh pentagon.POMDP_4_7
sbatch convex_slurm.sh sunysb.POMDP_4_7
