sbatch server_script.sh bell_state_reach bell_state_reach_0 "bellman convex" yorktown,ourense,jakarta,hanoi,cambridge,washington 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_1 "bellman convex" athens,essex,perfect_hardware,auckland 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_2 "bellman convex" vigo,manila,melbourne,montreal,rochester 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_3 "bellman convex" belem,london,guadalupe,mumbai,brooklyn 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_4 "bellman convex" valencia,lima,almaden,geneva,manhattan 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_5 "bellman convex" bogota,lagos,boeblingen,toronto 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_6 "bellman convex" santiago,perth,singapore,sydney 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_7 "bellman convex" rome,casablanca,johannesburg,cairo 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_8 "bellman convex" burlington,oslo,poughkeepsie,paris 1 7
sbatch server_script.sh bell_state_reach bell_state_reach_9 "bellman convex" quito,nairobi,kolkata,algiers 1 7
