sbatch server_script.sh cxh cxh_0 algiers,almaden,athens,auckland,belem
sbatch server_script.sh cxh cxh_1 boeblingen,bogota,brooklyn,burlington,cairo
sbatch server_script.sh cxh cxh_2 cambridge,casablanca,essex,geneva,guadalupe
sbatch server_script.sh cxh cxh_3 hanoi,jakarta,johannesburg,kolkata,lagos
sbatch server_script.sh cxh cxh_4 lima,london,melbourne,manhattan,manila
sbatch server_script.sh cxh cxh_5 montreal,mumbai,nairobi,oslo,ourense
sbatch server_script.sh cxh cxh_6 paris,perth,poughkeepsie,quito,rochester
sbatch server_script.sh cxh cxh_7 rome,santiago,singapore,sydney,toronto
sbatch server_script.sh cxh cxh_8 valencia,vigo,washington,yorktown,perfect_hardware
