sbatch server_script.sh cxh cxh_0 yorktown,jakarta,cambridge
sbatch server_script.sh cxh cxh_1 athens,perfect_hardware
sbatch server_script.sh cxh cxh_2 vigo,melbourne,rochester
sbatch server_script.sh cxh cxh_3 belem,guadalupe,brooklyn
sbatch server_script.sh cxh cxh_4 valencia,almaden,manhattan
sbatch server_script.sh cxh cxh_5 bogota,boeblingen
sbatch server_script.sh cxh cxh_6 santiago,singapore
sbatch server_script.sh cxh cxh_7 rome,johannesburg
sbatch server_script.sh cxh cxh_8 burlington,poughkeepsie
sbatch server_script.sh cxh cxh_9 quito,kolkata
sbatch server_script.sh cxh cxh_10 ourense,hanoi,washington
sbatch server_script.sh cxh cxh_11 essex,auckland
sbatch server_script.sh cxh cxh_12 manila,montreal
sbatch server_script.sh cxh cxh_13 london,mumbai
sbatch server_script.sh cxh cxh_14 lima,geneva
sbatch server_script.sh cxh cxh_15 lagos,toronto
sbatch server_script.sh cxh cxh_16 perth,sydney
sbatch server_script.sh cxh cxh_17 casablanca,cairo
sbatch server_script.sh cxh cxh_18 oslo,paris
sbatch server_script.sh cxh cxh_19 nairobi,algiers
