sbatch server_script.sh ipma ipma_0 yorktown,jakarta,cambridge
sbatch server_script.sh ipma ipma_1 athens,perfect_hardware
sbatch server_script.sh ipma ipma_2 vigo,melbourne,rochester
sbatch server_script.sh ipma ipma_3 belem,guadalupe,brooklyn
sbatch server_script.sh ipma ipma_4 valencia,almaden,manhattan
sbatch server_script.sh ipma ipma_5 bogota,boeblingen
sbatch server_script.sh ipma ipma_6 santiago,singapore
sbatch server_script.sh ipma ipma_7 rome,johannesburg
sbatch server_script.sh ipma ipma_8 burlington,poughkeepsie
sbatch server_script.sh ipma ipma_9 quito,kolkata
sbatch server_script.sh ipma ipma_10 ourense,hanoi,washington
sbatch server_script.sh ipma ipma_11 essex,auckland
sbatch server_script.sh ipma ipma_12 manila,montreal
sbatch server_script.sh ipma ipma_13 london,mumbai
sbatch server_script.sh ipma ipma_14 lima,geneva
sbatch server_script.sh ipma ipma_15 lagos,toronto
sbatch server_script.sh ipma ipma_16 perth,sydney
sbatch server_script.sh ipma ipma_17 casablanca,cairo
sbatch server_script.sh ipma ipma_18 oslo,paris
sbatch server_script.sh ipma ipma_19 nairobi,algiers
