sbatch server_script.sh ipma2 ipma2_0 yorktown,hanoi
sbatch server_script.sh ipma2 ipma2_1 athens,auckland
sbatch server_script.sh ipma2 ipma2_2 vigo,montreal
sbatch server_script.sh ipma2 ipma2_3 belem,mumbai
sbatch server_script.sh ipma2 ipma2_4 valencia,geneva
sbatch server_script.sh ipma2 ipma2_5 bogota,toronto
sbatch server_script.sh ipma2 ipma2_6 santiago,sydney
sbatch server_script.sh ipma2 ipma2_7 rome,cairo
sbatch server_script.sh ipma2 ipma2_8 burlington,paris
sbatch server_script.sh ipma2 ipma2_9 quito,algiers
sbatch server_script.sh ipma2 ipma2_10 ourense,cambridge
sbatch server_script.sh ipma2 ipma2_11 essex
sbatch server_script.sh ipma2 ipma2_12 manila,rochester
sbatch server_script.sh ipma2 ipma2_13 london,brooklyn
sbatch server_script.sh ipma2 ipma2_14 lima,manhattan
sbatch server_script.sh ipma2 ipma2_15 lagos
sbatch server_script.sh ipma2 ipma2_16 perth
sbatch server_script.sh ipma2 ipma2_17 casablanca
sbatch server_script.sh ipma2 ipma2_18 oslo
sbatch server_script.sh ipma2 ipma2_19 nairobi
sbatch server_script.sh ipma2 ipma2_20 jakarta,washington
sbatch server_script.sh ipma2 ipma2_21 perfect_hardware
sbatch server_script.sh ipma2 ipma2_22 melbourne
sbatch server_script.sh ipma2 ipma2_23 guadalupe
sbatch server_script.sh ipma2 ipma2_24 almaden
sbatch server_script.sh ipma2 ipma2_25 boeblingen
sbatch server_script.sh ipma2 ipma2_26 singapore
sbatch server_script.sh ipma2 ipma2_27 johannesburg
sbatch server_script.sh ipma2 ipma2_28 poughkeepsie
sbatch server_script.sh ipma2 ipma2_29 kolkata
