sbatch server_script.sh lbell lbell_0 yorktown,ourense,jakarta,hanoi,cambridge,washington
sbatch server_script.sh lbell lbell_1 athens,essex,perfect_hardware,auckland
sbatch server_script.sh lbell lbell_2 vigo,manila,melbourne,montreal,rochester
sbatch server_script.sh lbell lbell_3 belem,london,guadalupe,mumbai,brooklyn
sbatch server_script.sh lbell lbell_4 valencia,lima,almaden,geneva,manhattan
sbatch server_script.sh lbell lbell_5 bogota,lagos,boeblingen,toronto
sbatch server_script.sh lbell lbell_6 santiago,perth,singapore,sydney
sbatch server_script.sh lbell lbell_7 rome,casablanca,johannesburg,cairo
sbatch server_script.sh lbell lbell_8 burlington,oslo,poughkeepsie,paris
sbatch server_script.sh lbell lbell_9 quito,nairobi,kolkata,algiers
