sbatch server_script.sh lphase lphase_0 yorktown,jakarta,cambridge
sbatch server_script.sh lphase lphase_1 athens,perfect_hardware
sbatch server_script.sh lphase lphase_2 vigo,melbourne,rochester
sbatch server_script.sh lphase lphase_3 belem,guadalupe,brooklyn
sbatch server_script.sh lphase lphase_4 valencia,almaden,manhattan
sbatch server_script.sh lphase lphase_5 bogota,boeblingen
sbatch server_script.sh lphase lphase_6 santiago,singapore
sbatch server_script.sh lphase lphase_7 rome,johannesburg
sbatch server_script.sh lphase lphase_8 burlington,poughkeepsie
sbatch server_script.sh lphase lphase_9 quito,kolkata
sbatch server_script.sh lphase lphase_10 ourense,hanoi,washington
sbatch server_script.sh lphase lphase_11 essex,auckland
sbatch server_script.sh lphase lphase_12 manila,montreal
sbatch server_script.sh lphase lphase_13 london,mumbai
sbatch server_script.sh lphase lphase_14 lima,geneva
sbatch server_script.sh lphase lphase_15 lagos,toronto
sbatch server_script.sh lphase lphase_16 perth,sydney
sbatch server_script.sh lphase lphase_17 casablanca,cairo
sbatch server_script.sh lphase lphase_18 oslo,paris
sbatch server_script.sh lphase lphase_19 nairobi,algiers
