sbatch server_script.sh lphase2 lphase2_0 yorktown,jakarta,cambridge
sbatch server_script.sh lphase2 lphase2_1 athens,perfect_hardware
sbatch server_script.sh lphase2 lphase2_2 vigo,melbourne,rochester
sbatch server_script.sh lphase2 lphase2_3 belem,guadalupe,brooklyn
sbatch server_script.sh lphase2 lphase2_4 valencia,almaden,manhattan
sbatch server_script.sh lphase2 lphase2_5 bogota,boeblingen
sbatch server_script.sh lphase2 lphase2_6 santiago,singapore
sbatch server_script.sh lphase2 lphase2_7 rome,johannesburg
sbatch server_script.sh lphase2 lphase2_8 burlington,poughkeepsie
sbatch server_script.sh lphase2 lphase2_9 quito,kolkata
sbatch server_script.sh lphase2 lphase2_10 ourense,hanoi,washington
sbatch server_script.sh lphase2 lphase2_11 essex,auckland
sbatch server_script.sh lphase2 lphase2_12 manila,montreal
sbatch server_script.sh lphase2 lphase2_13 london,mumbai
sbatch server_script.sh lphase2 lphase2_14 lima,geneva
sbatch server_script.sh lphase2 lphase2_15 lagos,toronto
sbatch server_script.sh lphase2 lphase2_16 perth,sydney
sbatch server_script.sh lphase2 lphase2_17 casablanca,cairo
sbatch server_script.sh lphase2 lphase2_18 oslo,paris
sbatch server_script.sh lphase2 lphase2_19 nairobi,algiers
