sbatch server_script.sh reset reset_0 yorktown,ourense,jakarta,hanoi,cambridge,washington
sbatch server_script.sh reset reset_1 athens,essex,perfect_hardware,auckland,prague,kyiv
sbatch server_script.sh reset reset_2 vigo,manila,melbourne,montreal,rochester,torino
sbatch server_script.sh reset reset_3 belem,london,guadalupe,mumbai,brooklyn,fez
sbatch server_script.sh reset reset_4 valencia,lima,almaden,geneva,manhattan,makarresh
sbatch server_script.sh reset reset_5 bogota,lagos,boeblingen,toronto,cusco
sbatch server_script.sh reset reset_6 santiago,perth,singapore,sydney,brisbane
sbatch server_script.sh reset reset_7 rome,casablanca,johannesburg,cairo,kawasaki
sbatch server_script.sh reset reset_8 burlington,oslo,poughkeepsie,paris,osaka
sbatch server_script.sh reset reset_9 quito,nairobi,kolkata,algiers,kyoto
